name: TableToolWebDart
description: Dart Table Tool
version: 0.0.1
#homepage: https://www.example.com
#author: paytmock <email@example.com>

environment:
  sdk: ^2.0.0

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0

transformers:
- dart_to_js_script_rewriter